### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by greyhub** [hxt365/terminal#2]
Link demo lỗi à bạn ?
![image](https://user-images.githubusercontent.com/65758619/106290289-de4d3280-627c-11eb-82da-eb3fcc38cc42.png)

**Comment by hxt365** [comment]
Bên này vẫn vào được bạn ạ. Có khi do bọn Heroku bị lỗi. Check lại thử xem sao bạn
![Screenshot from 2021-01-29 18-02-43](https://user-images.githubusercontent.com/16115992/106291052-358edb00-625c-11eb-8693-0b68c21c3822.png)

**Comment by greyhub** [comment]
oke, được rồi nhé

**Comment by hxt365** [comment]
Có gì cho feedback nhé bạn
